version: '3'

services:
  web:
    build: .
    image: myapp
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - 80:8000
    env_file:
      - ./.env